"""Core MLX utilities for the irodori-tts-mlx prototype."""

from .config import ModelConfig
from .duration import build_duration_features
from .encoders import (
    ConditionEncoders,
    EncodedConditions,
    ReferenceLatentEncoder,
    SelfAttention,
    TextBlock,
    TextEncoder,
    masked_mean_token,
)
from .model import DiffusionBlock, JointAttention, TextToLatentRFDiT
from .sampling import euler_timestep_schedule, sample_euler_rf_cfg
from .runtime import (
    DACVAEBridgeConfig,
    GenerationRequest,
    GenerationResult,
    MLXDACVAERuntime,
    MLXRuntimeConfig,
    PretrainedTextTokenizer,
    PyTorchDACVAEBridge,
    iter_messages,
    load_mlx_model,
    load_model_config_json,
    mlx_to_torch_latents,
    save_wav,
    torch_to_mlx_latents,
)
from .layers import (
    LowRankAdaLN,
    RMSNorm,
    SwiGLU,
    apply_rotary_emb,
    get_timestep_embedding,
    patch_latents,
    patch_sequence_with_mask,
    precompute_freqs_cis,
    unpatch_latents,
)
from .weights import WeightLoadReport, assign_named_weights, encoder_required_keys, load_npz_weights, rf_dit_required_keys

__all__ = [
    "ConditionEncoders",
    "DACVAEBridgeConfig",
    "DiffusionBlock",
    "EncodedConditions",
    "GenerationRequest",
    "GenerationResult",
    "JointAttention",
    "LowRankAdaLN",
    "MLXDACVAERuntime",
    "MLXRuntimeConfig",
    "ModelConfig",
    "PretrainedTextTokenizer",
    "PyTorchDACVAEBridge",
    "RMSNorm",
    "ReferenceLatentEncoder",
    "SelfAttention",
    "SwiGLU",
    "TextBlock",
    "TextEncoder",
    "TextToLatentRFDiT",
    "WeightLoadReport",
    "apply_rotary_emb",
    "assign_named_weights",
    "build_duration_features",
    "encoder_required_keys",
    "euler_timestep_schedule",
    "get_timestep_embedding",
    "iter_messages",
    "load_mlx_model",
    "load_model_config_json",
    "load_npz_weights",
    "masked_mean_token",
    "mlx_to_torch_latents",
    "patch_latents",
    "patch_sequence_with_mask",
    "precompute_freqs_cis",
    "rf_dit_required_keys",
    "sample_euler_rf_cfg",
    "save_wav",
    "torch_to_mlx_latents",
    "unpatch_latents",
]
